apiVersion: apps/v1
kind: Deployment
metadata:
  name: ba-account
  labels:
    app: ba-account
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ba-account
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ba-account
    spec:
      containers:
      - name: ba-account
        image: opsairegistry.azurecr.io/beyondauth-account:latest 
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: VaultUri
          valueFrom:
           secretKeyRef:
             name: "ba-account-secrets"
             key: "VaultUri"
        - name: TenantId
          valueFrom:
           secretKeyRef:
             name: "ba-account-secrets"
             key: "TenantId"
        - name: ClientId
          valueFrom:
           secretKeyRef:
             name: "ba-account-secrets"
             key: "ClientId"
        - name: ClientSecret
          valueFrom:
           secretKeyRef:
             name: "ba-account-secrets"
             key: "ClientSecret"
        ports:
        - containerPort: 443
          name: account-https
        - containerPort: 80
          name: account-http
        livenessProbe:
          httpGet:
            path: /hz
            port: account-http
            httpHeaders:
              - name: Accept
                value: text/html
          failureThreshold: 5
          periodSeconds: 20
          timeoutSeconds: 4
        startupProbe:
          httpGet:
            path: /hz
            port: account-http
            httpHeaders:
              - name: Accept
                value: text/html
          failureThreshold: 5
          periodSeconds: 60
          timeoutSeconds: 4
---
apiVersion: v1
kind: Service
metadata:
  name: ba-account-srv
spec:
  type: ClusterIP
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
    name: account-https
  - port: 80
    protocol: TCP
    targetPort: 80
    name: account-http
  selector:
    app: ba-account