# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '2090ed42-3209-4e98-bd10-118042d5815e'
  imageNameAudit: 'beyondauth-audit'
  imageNameAccount: 'beyondauth-account'
  imageNameAuth: 'beyondauth-auth'
  imageNameDocs: 'beyondauth-docs'
  imageNameIdp: 'beyondauth-idp'
  imageNamePolicy: 'beyondauth-policy'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    
    - task: gitversion/setup@0
      inputs:
        versionSpec: '5.x'
    
    - task: gitversion/execute@0
      inputs:
        updateAssemblyInfo: true
        updateAssemblyInfoFilename: '$(Build.SourcesDirectory)/src/AssemblyInfo.cs'
        additionalArguments: '/output buildserver'
        
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.0.100'

    - task: CmdLine@2
      inputs:
        script: 'sed -e ''s/latest/$(tag)/g'' ba-account-stg.yaml > $(Build.ArtifactStagingDirectory)/ba-account-stg.yml'
        workingDirectory: '$(Build.SourcesDirectory)/src/charts/'
    - task: CmdLine@2
      inputs:
        script: 'sed -e ''s/latest/$(tag)/g'' ba-account-prod.yaml > $(Build.ArtifactStagingDirectory)/ba-account-prod.yml'
        workingDirectory: '$(Build.SourcesDirectory)/src/charts/'
    - task: CmdLine@2
      inputs:
        script: 'sed -e ''s/latest/$(tag)/g'' ba-audit-stg.yaml > $(Build.ArtifactStagingDirectory)/ba-audit-stg.yml'
        workingDirectory: '$(Build.SourcesDirectory)/src/charts/'
    - task: CmdLine@2
      inputs:
        script: 'sed -e ''s/latest/$(tag)/g'' ba-audit-prod.yaml > $(Build.ArtifactStagingDirectory)/ba-audit-prod.yml'
        workingDirectory: '$(Build.SourcesDirectory)/src/charts/'
    - task: CmdLine@2
      inputs:
        script: 'sed -e ''s/latest/$(tag)/g'' ba-auth-stg.yaml > $(Build.ArtifactStagingDirectory)/ba-auth-stg.yml'
        workingDirectory: '$(Build.SourcesDirectory)/src/charts/'
    - task: CmdLine@2
      inputs:
        script: 'sed -e ''s/latest/$(tag)/g'' ba-auth-prod.yaml > $(Build.ArtifactStagingDirectory)/ba-auth-prod.yml'
        workingDirectory: '$(Build.SourcesDirectory)/src/charts/'
    - task: CmdLine@2
      inputs:
        script: 'sed -e ''s/latest/$(tag)/g'' ba-idp-stg.yaml > $(Build.ArtifactStagingDirectory)/ba-idp-stg.yml'
        workingDirectory: '$(Build.SourcesDirectory)/src/charts/'
    - task: CmdLine@2
      inputs:
        script: 'sed -e ''s/latest/$(tag)/g'' ba-idp-prod.yaml > $(Build.ArtifactStagingDirectory)/ba-idp-prod.yml'
        workingDirectory: '$(Build.SourcesDirectory)/src/charts/'
    - task: CmdLine@2
      inputs:
        script: 'sed -e ''s/latest/$(tag)/g'' ba-policy-stg.yaml > $(Build.ArtifactStagingDirectory)/ba-policy-stg.yml'
        workingDirectory: '$(Build.SourcesDirectory)/src/charts/'
    - task: CmdLine@2
      inputs:
        script: 'sed -e ''s/latest/$(tag)/g'' ba-policy-prod.yaml > $(Build.ArtifactStagingDirectory)/ba-policy-prod.yml'
        workingDirectory: '$(Build.SourcesDirectory)/src/charts/'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: '$(solution)'
        versioningScheme: 'byBuildNumber'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'charts'
        publishLocation: 'Container'

    - task: Docker@2
      displayName: Build Audit image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageNameAudit)'
        command: 'build'
        Dockerfile: 'src/AuditServer/Dockerfile'
        buildContext: 'src'
        tags: '$(tag)'
        arguments: '--build-arg VERSION=$(tag)'
    - task: Docker@2
      displayName: Push Audit image to container registry
      inputs:
        containerRegistry: 'opsairegistry'
        repository: '$(imageNameAudit)'
        command: 'push'

    - task: Docker@2
      displayName: Build Account image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageNameAccount)'
        command: 'build'
        Dockerfile: 'src/Authentication/Dockerfile'
        buildContext: 'src'
        tags: '$(tag)'
        arguments: '--build-arg VERSION=$(tag)'
    - task: Docker@2
      displayName: Push Account image to container registry
      inputs:
        containerRegistry: 'opsairegistry'
        repository: '$(imageNameAccount)'
        command: 'push'

    - task: Docker@2
      displayName: Build Auth image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageNameAuth)'
        command: 'build'
        Dockerfile: 'src/AuthorizationServer/Dockerfile'
        buildContext: 'src'
        tags: '$(tag)'
        arguments: '--build-arg VERSION=$(tag)'
    - task: Docker@2
      displayName: Push Auth image to container registry
      inputs:
        containerRegistry: 'opsairegistry'
        repository: '$(imageNameAuth)'
        command: 'push'
        
    - task: Docker@2
      displayName: Build IdP image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageNameIdp)'
        command: 'build'
        Dockerfile: 'src/IdentityManager/Dockerfile'
        buildContext: 'src'
        tags: '$(tag)'
        arguments: '--build-arg VERSION=$(tag)'
    - task: Docker@2
      displayName: Push IdP image to container registry
      inputs:
        containerRegistry: 'opsairegistry'
        repository: '$(imageNameIdp)'
        command: 'push'

    - task: Docker@2
      displayName: Build Policy image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageNamePolicy)'
        command: 'build'
        Dockerfile: 'src/PolicyServer/Dockerfile'
        buildContext: 'src'
        tags: '$(tag)'
        arguments: '--build-arg VERSION=$(tag)'
    - task: Docker@2
      displayName: Push Policy image to container registry
      inputs:
        containerRegistry: 'opsairegistry'
        repository: '$(imageNamePolicy)'
        command: 'push'
