version: '3.4'

services:
  authentication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/beyondauth.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=c582b846-0fef-4144-b28a-9c343644768f
    ports:
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  policyserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/beyondauth.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=c582b846-0fef-4144-b28a-9c343644768f
    ports:
      - "5002:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  authorizationserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/beyondauth.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=c582b846-0fef-4144-b28a-9c343644768f
    ports:
      - "5003:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  auditserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/beyondauth.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=c582b846-0fef-4144-b28a-9c343644768f
    ports:
      - "5004:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  beyondauth.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/beyondauth.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=c582b846-0fef-4144-b28a-9c343644768f
    ports:
      - "5005:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  radiusserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/beyondauth.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=c582b846-0fef-4144-b28a-9c343644768f
    ports:
      - "5006:443"

      
  openldap:
    environment:
      - LDAP_ORGANISATION=Contoso Ltd.
      - LDAP_DOMAIN=contoso.com
      - LDAP_ADMIN_PASSWORD=P@ss1W0Rd!
      - LDAP_CONFIG_PASSWORD=P@ss1W0Rd!
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=ldap-ro
      - LDAP_READONLY_USER_PASSWORD=P@ss1W0Rd!
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - ./OpenLdap/ldap:/data/ldif

  zookeeper:
    ports:
      - "2181:2181"
      
  kafka:
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.10.11.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    