version: '3.4'

services:
  authentication:
    image: ${DOCKER_REGISTRY-}authentication
    build:
      context: .
      dockerfile: Authentication/Dockerfile

  policyserver:
    image: ${DOCKER_REGISTRY-}policyserver
    build:
      context: .
      dockerfile: PolicyServer/Dockerfile

  authorizationserver:
    image: ${DOCKER_REGISTRY-}authorizationserver
    build:
      context: .
      dockerfile: AuthorizationServer/Dockerfile

  auditserver:
    image: ${DOCKER_REGISTRY-}auditserver
    build:
      context: .
      dockerfile: AuditServer/Dockerfile

  beyondauthweb:
    image: ${DOCKER_REGISTRY-}beyondauthweb
    build:
      context: .
      dockerfile: BeyondAuth.Web/Dockerfile

  identitymanager:
    image: ${DOCKER_REGISTRY-}identitymanager
    build:
      context: .
      dockerfile: IdentityManager/Dockerfile
      
  documentation:
    image: ${DOCKER_REGISTRY-}documentation
    build:
      context: .
      dockerfile: Documentation/Dockerfile

  #radiusserver:
  #  image: ${DOCKER_REGISTRY-}radiusserver
  #  build:
  #    context: ./Bridges
  #    dockerfile: RadiusServer/Dockerfile

  openldap:
    #container_name: ${DOCKER_REGISTRY-}openldap
    image: osixia/openldap:latest

  zookeeper:
    image: wurstmeister/zookeeper
      
  kafka:
    image: wurstmeister/kafka

