version: '3.4'

services:
  authentication:
    image: ${DOCKER_REGISTRY-}authentication
    build:
      context: .
      dockerfile: Authentication/Dockerfile

  policyserver:
    image: ${DOCKER_REGISTRY-}policyserver
    build:
      context: .
      dockerfile: PolicyServer/Dockerfile

  authorizationserver:
    image: ${DOCKER_REGISTRY-}authorizationserver
    build:
      context: .
      dockerfile: AuthorizationServer/Dockerfile

  auditserver:
    image: ${DOCKER_REGISTRY-}auditserver
    build:
      context: .
      dockerfile: AuditServer/Dockerfile

  beyondauth.web:
    image: ${DOCKER_REGISTRY-}beyondauthweb
    build:
      context: .
      dockerfile: BeyondAuth.Web/Dockerfile

  radiusserver:
    image: ${DOCKER_REGISTRY-}radiusserver
    build:
      context: .
      dockerfile: RadiusServer/Dockerfile

  openldap:
    container_name: ${DOCKER_REGISTRY-}openldap
    image: osixia/openldap:latest
    ports: 
      - "389:389"
      - "636:636"
    env_file:
      - ./OpenLdap/ldap.env
    volumes:
      - ./OpenLdap/ldap:/data/ldif


